# Check MisClassified label

In [12]:
from keras.models import load_model
from keras.datasets import mnist
from keras.utils import to_categorical
import cv2

#load data
(x_train,y_train), (x_test,y_test) = mnist.load_data()

# prepare our dataset -> do only x_test (x_train not use)
input_shape = (x_test.shape[0],28,28,1)
x_test = x_test.reshape(input_shape)
x_test = x_test.astype('float32')
x_test /= 255

y_test = to_categorical(y_test)


# load our model from hand writing recognition
MODEL_DIR = "handwritten recognition MNIST/HandwrittenRecognition_MNIST_simpleCNN.h5"
model = load_model(MODEL_DIR)

In [32]:
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

#predict class
y_pred = model.predict_classes(x_test)

In [33]:
# show our classification report
print(classification_report(np.argmax(y_test,axis=1),y_pred))
# use argmax because -> y_test is vector of class like this -> [0,0,0,1,0,0,0,0,0,0]  use argmax to get position of 1

              precision    recall  f1-score   support

           0       0.98      0.99      0.98       980
           1       0.99      0.99      0.99      1135
           2       0.98      0.99      0.98      1032
           3       0.97      0.99      0.98      1010
           4       0.99      0.99      0.99       982
           5       0.98      0.98      0.98       892
           6       0.99      0.98      0.99       958
           7       0.99      0.97      0.98      1028
           8       0.98      0.98      0.98       974
           9       0.99      0.97      0.98      1009

    accuracy                           0.98     10000
   macro avg       0.98      0.98      0.98     10000
weighted avg       0.98      0.98      0.98     10000



In [34]:
# show our confustion matrix
print(confusion_matrix(np.argmax(y_test,axis=1),y_pred))

[[ 972    2    1    1    0    1    2    0    0    1]
 [   0 1123    2    3    0    0    1    3    2    1]
 [   0    4 1023    3    0    0    0    2    0    0]
 [   0    0    2 1003    0    4    0    0    1    0]
 [   0    0    2    0  969    0    3    1    2    5]
 [   1    0    0   12    0  873    1    0    5    0]
 [  10    3    1    0    1    4  937    0    2    0]
 [   0    0   12    5    2    1    0 1001    2    5]
 [   7    2    3    5    1    1    0    2  951    2]
 [   6    2    3    3    9    7    0    2    3  974]]


# display our misclassified data

In [45]:
(x_train,y_train), (x_test,y_test) = mnist.load_data()

In [46]:
result = np.absolute(y_test-y_pred)
result_indices = np.nonzero(result)

print(result_indices)

(array([  18,   43,  115,  151,  259,  266,  282,  445,  497,  543,  582,
        619,  659,  674,  717,  720,  726,  740,  810,  882,  883,  947,
        965, 1014, 1033, 1039, 1107, 1181, 1226, 1232, 1247, 1414, 1459,
       1522, 1527, 1549, 1621, 1641, 1673, 1691, 1709, 1717, 1737, 1878,
       1901, 1955, 1969, 2016, 2018, 2035, 2043, 2053, 2093, 2118, 2129,
       2130, 2135, 2182, 2280, 2293, 2343, 2369, 2380, 2387, 2406, 2414,
       2454, 2526, 2573, 2597, 2648, 2654, 2695, 2730, 2896, 2921, 2927,
       2939, 2953, 2995, 3005, 3030, 3073, 3100, 3171, 3206, 3422, 3451,
       3503, 3520, 3558, 3559, 3597, 3601, 3730, 3767, 3778, 3780, 3808,
       3838, 3869, 3906, 3926, 3941, 4015, 4065, 4075, 4078, 4086, 4176,
       4265, 4284, 4360, 4369, 4382, 4384, 4399, 4536, 4547, 4571, 4575,
       4578, 4740, 4743, 4761, 4807, 4814, 4837, 4874, 4956, 5246, 5634,
       5642, 5654, 5676, 5887, 5937, 5982, 5997, 6091, 6172, 6505, 6572,
       6597, 6599, 6603, 6625, 6632, 6651, 6740, 7

In [40]:
# because i download dataset again so i have to prepare data again
x_test = x_test.reshape(x_test.shape[0],28,28,1)

In [41]:
num_test = 10
for i in range(num_test):
    input_im = x_test[result_indices[0][i]]
#     input_im = input_im.reshape
#     res = model.predict_classes(input_im,1,verbose=0)[0]
    print(input_im.shape)
    

ValueError: in user code:

    C:\Users\Prayat\Anaconda3\envs\computer_vision\lib\site-packages\tensorflow\python\keras\engine\training.py:1147 predict_function  *
        outputs = self.distribute_strategy.run(
    C:\Users\Prayat\Anaconda3\envs\computer_vision\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:951 run  **
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    C:\Users\Prayat\Anaconda3\envs\computer_vision\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2290 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    C:\Users\Prayat\Anaconda3\envs\computer_vision\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2649 _call_for_each_replica
        return fn(*args, **kwargs)
    C:\Users\Prayat\Anaconda3\envs\computer_vision\lib\site-packages\tensorflow\python\keras\engine\training.py:1122 predict_step  **
        return self(x, training=False)
    C:\Users\Prayat\Anaconda3\envs\computer_vision\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:885 __call__
        input_spec.assert_input_compatibility(self.input_spec, inputs,
    C:\Users\Prayat\Anaconda3\envs\computer_vision\lib\site-packages\tensorflow\python\keras\engine\input_spec.py:176 assert_input_compatibility
        raise ValueError('Input ' + str(input_index) + ' of layer ' +

    ValueError: Input 0 of layer sequential_2 is incompatible with the layer: expected ndim=4, found ndim=3. Full shape received: [1, 28, 1]
